
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/esmdb
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
  security:
    user:
      name: postgres
      password: 123456789
  error:
    whitelabel:
      enabled: false
    path: /error
server:
  error:
    path: /error

cloudinary:
  cloud-name: ${BR10_CLOUDINARY_CLOUD_NAME:dhhlnrons}
  api-key: ${BR10_CLOUDINARY_CLOUD_NAME:712786691512151}
  api-secret: ${BR10_CLOUDINARY_CLOUD_NAME:AIp9AEAYuHYk_IQqDDozHF4Ew9M}